### ISSUE TITLE
Bug提交

### ISSUE THREAD

**Issue by wmss-wj** [maxsky/Yahei-Monaco-Hybird-Font#1]
## BUG1
在IntelliJ IDEA中选择字体时字体名如下   
![image](https://user-images.githubusercontent.com/21033925/27024601-bc0c51b0-4f89-11e7-8354-7a787c671e56.png)
选择完成字体名又正常了   
![image](https://user-images.githubusercontent.com/21033925/27024627-e0abaaca-4f89-11e7-9d6f-758a4d533197.png)
## BUG 2
文字乱码   
这是Consolas字体下的自动生成的注释   
![image](https://user-images.githubusercontent.com/21033925/27024714-48f88724-4f8a-11e7-8bbe-0b85ba53394f.png)
这是你的字体   
![image](https://user-images.githubusercontent.com/21033925/27024793-9dc8022a-4f8a-11e7-9cd3-38bd83c0b978.png)
（虽然我觉得这有可能是IDEA的bug）
对了你的字体预览在IDEA中是这样的
![image](https://user-images.githubusercontent.com/21033925/27024849-e0ac1f68-4f8a-11e7-9b1f-27c9da6ec4d0.png)

最后两张对比图
![image](https://user-images.githubusercontent.com/21033925/27025121-e690d94a-4f8b-11e7-8c85-58e4d7c3cb8a.png)
![image](https://user-images.githubusercontent.com/21033925/27025139-f7df9efc-4f8b-11e7-9910-8e4d00d0dcef.png)

**Comment by maxsky** [comment]
你下错版本了吧，你这个好像是旧版本的，下新版本试试 [YaHeiMonacoHybird.zip](https://github.com/maxsky/Yahei-Monaco-Hybird-Font/files/1059708/YaHeiMonacoHybird.zip)
旧版本叫 Yahei Monaco Hybird，1.2 修正版是 YaHei Monaco Hybird.  Yahei 和 YaHei 的区别。
