### ISSUE TITLE
idea2018.3使用这个字体

### ISSUE THREAD

**Issue by sunhao-java** [maxsky/Yahei-Monaco-Hybird-Font#10]
idea2018.3 需要安装字体文件时,右键选择为`所有用户安装`,要不然idea识别不了这个字体

**Comment by zxj5470** [comment]
补充说明一下，以前的安装字体文件双击以后是有一个UAC标识（但是现在可能是windows版本高了的原因所以没有？）

Translation：
Lagacy windows(7<=version<=17173?) has a UAC logo when installing, but a higher version not.

**Comment by maxsky** [comment]
> 补充说明一下，以前的安装字体文件双击以后是有一个UAC标识（但是现在可能是windows版本高了的原因所以没有？）
> 
> Translation：
> Lagacy windows(7<=version<=17173?) has a UAC logo when installing, but a higher version not.

Windows 7 通过控制面板中关闭 UAC 后重启，对于系统来说是完全关闭，即拥有 C 盘完整的操作权。而 Windows 8 开始，通过控制面板中关闭 UAC（拉到最低），也只是关闭了带盾牌图标的程序/功能执行时的弹框提示，如果要完全关闭需要进组策略修改，但是从 Windows 8/8.1 来看关闭后 Metro 应用失效。那个盾牌图标代表的就是该操作是一个权限比较高的操作，Win7/2008 里面我刚看了一下是有的。Windows 10 不记得啦...大概是有的吧？如果没有是不是已经安装过了才没有的。
