### ISSUE TITLE
有些字母有一点点发虚

### ISSUE THREAD

**Issue by ghost** [maxsky/Yahei-Monaco-Hybird-Font#7]
比较容易看出来的是 t、l ，上面有一点发虚，字体越小越明显。

**Comment by maxsky** [comment]
嗯嗯，这个问题在制作的时候发现了，主要是 Monaco 字体我在 Mac 上因为是 2K 屏所以看着没问题，在 Win 上 1080P 及以下屏幕的话偏小时会出现这个问题的...Sorry 目前没法修复
