### ISSUE TITLE
【字体方向错误】字体挺好的，但还得维护起来。

### ISSUE THREAD

**Issue by yl-yue** [maxsky/Yahei-Monaco-Hybird-Font#8]
![image](https://user-images.githubusercontent.com/39790401/50428094-34f22080-08ef-11e9-9623-50c2b7a6b3f0.png)

字体方向错误。

**Comment by maxsky** [comment]
-。- 我感觉我已经放弃啦 哈哈哈

**Comment by yl-yue** [comment]
若是平常编码用的是这款字体，应该会发现一些不足，就慢慢的优化他。使之成为国内程序员的标配字体.

**Comment by yl-yue** [comment]
> -。- 我感觉我已经放弃啦 哈哈哈

若是平常编码用的是这款字体，应该会发现一些不足，就慢慢的优化他。使之成为国内程序员的标配字体.

**Comment by maxsky** [comment]
是的，平时在 Mac 上 IDEA 里面一直用的 Monaco，因为 2K 屏觉得挺好看的，有一天在 Win 上苦于找不到漂亮的字体就想着混一个。主要是有的字得一个个慢慢调，有兴趣的话 Release 里面有 FontForge 的源文件可以试试。

**Comment by yl-yue** [comment]
> 是的，平时在 Mac 上 IDEA 里面一直用的 Monaco，因为 2K 屏觉得挺好看的，有一天在 Win 上苦于找不到漂亮的字体就想着混一个。主要是有的字得一个个慢慢调，有兴趣的话 Release 里面有 FontForge 的源文件可以试试。

是我搞错了不好意思，win10安装字体时，有@开头的是躺过的字体。

**Comment by maxsky** [comment]
我就是不好意思告诉你 哈哈哈...

**Comment by yl-yue** [comment]
> 我就是不好意思告诉你 哈哈哈...

这就尴尬了，我是来寻求解决方案的...

**Comment by shawphy** [comment]
hhhh，既然解决了就 close 掉吧

**Comment by maxsky** [comment]
走你
